### ISSUE TITLE
Synthesis UI upgrade causes error in this patcher

### ISSUE THREAD

**Issue by Glanzer-modder** [Jampi0n/Skyrim-RemoveLandscapeVertexColor#1]
Hi Jampi0n, the Synthesis UI was updated today and it causes the following error when using your patcher:

LandscapeGrid.cs(162,53): error CS1061: 'IArray2d<P3UInt8>' does not contain a definition for 'Value' 

I had to set it to run with a prior version to make it work. Just letting you know!

**Comment by Jampi0n** [comment]
It should work now with the latest mutagen version. 0.37 comes with a new landscape API, that's why it didn't work initially.

0.37 was in the works for a while and had some prereleases, so I could already adapt the patcher for the new API. I just had to wait until the official release of 0.37 to push my updates.
